# Generated by Django 4.1.7 on 2023-03-05 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Threads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='participants',
            field=models.ManyToManyField(limit_choices_to={'participants__count': 2}, related_name='threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
